# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3b6782934144deea88119032d2cf7dd244786794b6f55b4b33ecf9091167caf854efa27ce72e23499d9508a6fa05e66ff742ee86aaf5258ea43e1aa02cdc205

test:
  secret_key_base: 578b1214b201229fe1c6d73d903001eb65ed9d77317189584f4ac6553a910394fbbd43fc3fe65f3725fe965811632cf6a46341cfa3caa122214e52995ea6f884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
